# Generated by Django 5.2 on 2025-04-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image_file', models.ImageField(upload_to='media/')),
                ('processed', models.BooleanField(default=False)),
                ('result', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('capture_date', models.DateTimeField(blank=True, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('drone_model', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_settings', models.JSONField(blank=True, null=True)),
                ('orientation', models.JSONField(blank=True, null=True)),
                ('exif_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
